### PR TITLE
Add php 8 support

### PR DESCRIPTION
**Pull request by lasseeee**

### CODE REVIEW

**Comment by octoper** [comment]
@lasseeee waiting for [Laravel Zero](https://github.com/laravel-zero/laravel-zero) to add support for PHP 8 https://github.com/laravel-zero/framework/pull/421 and you will need to update to latest `laravel-zero/framework` too when it will be available.

**Comment by owenvoke** [comment]
Just a heads up, Laravel Zero v8.4.0 has now been released with support for PHP 8. 👍🏻

**Comment by lahivee** [comment]
There should be a service where you can donate to "push" for a pending version upgrade PR to get merged :D 

cc @mpociot 1. as a reminder (because I think this notifications can slip through) and 2. as an idea for another project 👀

**Comment by Iamscaredofcode** [comment]
can this be merged, or what are we waiting for here?

**Comment by octoper** [comment]
I think he will need to change the version of `laravel-zero/framework` from `8.0` to `8.5` and it will be ready to merge cc @lasseeee

**Comment by lasseeee** [comment]
`laravel-zero/framework` is required at `^8.0` and should pick up the minor release where PHP 8.0 support was added (v8.4) without any change to the pull request, or am I mistaken?

**Comment by lahivee** [comment]
yea actually think so too. Does composer install cause any errors with fresh composer.lock file? If not then we are good to go

**Comment by lahivee** [comment]
Anyways, I think bumping the version quickly to v8.4 would be 'the right' thing to do @lasseeee

**Comment by quarterdeck** [comment]
This is a great little utility but it's unfortunately holding up upgrading my system to PHP8, I'd rather not have to remove it.

I'll do you a deal @mpociot, if we can get PHP8 support added I'll renew my Tinkerwell license. 😜

**Comment by mpociot** [comment]
Thank you!

**Pull request merged**
