### PR TITLE
Add webhooks commands

### PR DESCRIPTION
**Pull request by squatto**
This adds the following commands:

* `webhooks:list`
* `webhooks:create {url}`
* `webhooks:delete {id?}`

I have some more commands in the works too ;)

Thanks!

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for the PR.

I don't want this project to become a "standard" Forge CLI tool. My intention was to create something similar to how Laravel Vapor allows you to manage (and link) your applications and your application configuration from the CLI.

The main benefit is that some parts of your site configuration are living under source control (in the forge.yml file).

So instead of having a `webhooks:xxx` command, I would prefer that we synchronize the existing webhooks and write them to the `forge.yml` file when doing `forge init`.
And then there should be a different command that syncs your configuration back to Forge.

So instead of adding a new webhook via `forge webhooks:create https://my-url.com` you would just add it to your forge.yml file, run `forge config:push` (or whatever) and this would:

- Update the deployment script
- Create non-existing webhooks on Forge
- Delete webhooks that are no longer in your yml file
- etc.

Let me know if you would be up to create a PR for some of these changes.

I hope you understand the direction that I want to go with that project.

**Comment by mpociot** [comment]
I actually thought about this some more and maybe we can do it both ways.
So adding a webhook via the webhook:create command would add it to Forge + add it to the forge.yml file immediately.

What do you think?

**Comment by squatto** [comment]
I like that path quite a bit, actually. A [Blueprint](https://github.com/laravel-shift/blueprint) for Forge, if you will.

Making the commands essentially wrappers around updating the config file and syncing the changes to Forge is a great idea! I will update my code to keep a `webhooks` node in sync in `forge.yml`.

Do you want to put together the base process for pushing/syncing Forge with the config file? I envision something along the lines of individual classes that handle the Forge/config sync for each resource. Just spitballing here (and programming straight into the GitHub box), but maybe something like this?

```php
namespace App\Sync;

use App\Support\Configuration;
use Laravel\Forge\Forge;

abstract class BaseSync
{
    /** @var Forge */
	protected $forge;

    /** @var Configuration */
	protected $config;

    /** @var int */
    protected $serverId;

    /** @var int */
    protected $siteId;

    public function __construct(Forge $forge, Configuration $config)
    {
        $this->forge = $forge;
        $this->config = $config;
        $this->serverId = $config->get('server');
        $this->siteId = $config->get('id');
    }

    public function sync(): void;
}
```

```php
namespace App\Sync;

use Laravel\Forge\Resources\Webhook;

class Webhooks extends BaseSync
{
    public function sync(): void
    {
        /** @var Webhook[] */
        $forgeWebhooks = $this->forge->webhooks($this->serverId, $this->siteId);

        $configWebhooks = $this->config->get('webhooks');

        // update Forge to match forge.yml:
        // - loop $forgeWebhooks and delete any that aren't in $configWebhooks
        // - loop $configWebhooks and create any that aren't in $forgeWebhooks
    }
}
```

**Comment by squatto** [comment]
There are a few commands in the API/SDK that aren't related to configuration that I think could be beneficial to include in this package. I can add them if you feel that they should be added. Let me know what you think:

* `deploy:log` - view the latest deployment log
* `reboot:server`
* `reboot:mysql`
* `reboot:postgres`
* `reboot:nginx`

These would be helpful utility commands:

* `open` - open the current site in a browser
* `forge` or `open:forge` (not sure on the name on this one...) - open the current site in Forge in a browser

In case you haven't already seen it, I wanted to show you what F-Bar gives you per-site. That's where some of these ideas came from:

image

**Comment by mpociot** [comment]
Yeah I like this set of commands:

> deploy:log - view the latest deployment log
deploy:reset - reset deployment state
reboot:server
reboot:mysql
reboot:postgres
reboot:nginx
>
> These would be helpful utility commands:
>
>open - open the current site in a browser
forge or open:forge (not sure on the name on this one...) - open the current site in Forge in a browser

And your idea with the different sync classes is also good.
Right now, the initial configuration state is defined in the Configuration class itself, where there is a `getConfigFormat` method: https://github.com/beyondcode/forge-cli/blob/master/app/Support/Configuration.php#L45

So when you run `forge:init` and either link an existing site, or create a new one, this format will be used for the YML file.

One thing we should pay attention to, is add a warning/confirmation, if the data on Forge holds more information than the YML file. 
For example, when someone creates a queue worker manually via the Forge UI, but the YML file does not contain it, we should throw a warning, that the local configuration might be outdated - or you can use an option like `--force` to overwrite all Forge changes with the state of the YML file.

**Comment by mpociot** [comment]
I added a first draft of the Webhook sync: https://github.com/beyondcode/forge-cli/commit/68a11369c648206805cf24f25ff8cda4a10d785d

**Comment by squatto** [comment]
Perfect, I'll get those commands put together and send up a PR soon!

The config push/pull/sync process looks great! I agree about being very careful with the remote changes. I like what you did with the `--force` option - requiring an explicit opt-in to actually make the changes puts the onus on the user. AKA shifts the blame when things go wrong 😂

**Pull request closed without merging**
